# Generated by Django 3.2.23 on 2024-03-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subfamily',
            fields=[
                ('idsubfamily', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('namesubfamily', models.CharField(max_length=150)),
            ],
        ),
    ]
