# Generated by Django 3.2.23 on 2024-03-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorisationRes',
            fields=[
                ('idauthorisation', models.AutoField(primary_key=True, serialize=False)),
                ('name_authorisation', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'authorisation_res',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'author_species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Botanist',
            fields=[
                ('idbotanist', models.AutoField(primary_key=True, serialize=False)),
                ('namebotanist', models.CharField(blank=True, max_length=150, null=True)),
                ('function_botanist', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'botanist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectGathering',
            fields=[
                ('idcollect', models.AutoField(primary_key=True, serialize=False)),
                ('numbercollect', models.CharField(blank=True, max_length=150, null=True)),
                ('commentary', models.CharField(blank=True, max_length=500, null=True)),
                ('collector_number', models.CharField(blank=True, max_length=150, null=True)),
                ('herb_location', models.CharField(blank=True, max_length=150, null=True)),
                ('collector_name', models.CharField(max_length=150)),
                ('year_collect', models.CharField(blank=True, max_length=50, null=True)),
                ('location_gathering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collect_gathering',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'collect_species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('idcontinent', models.AutoField(primary_key=True, serialize=False)),
                ('namecontinent', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'continent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistributionSpecies',
            fields=[
                ('iddistribution', models.AutoField(primary_key=True, serialize=False)),
                ('accepted_name', models.CharField(blank=True, max_length=150, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ddlong', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('ddlat', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('col_date', models.CharField(blank=True, max_length=150, null=True)),
                ('col_year', models.CharField(blank=True, max_length=150, null=True)),
                ('det_by', models.CharField(blank=True, max_length=9000, null=True)),
                ('det_year', models.CharField(blank=True, max_length=150, null=True)),
                ('det_date', models.CharField(blank=True, max_length=150, null=True)),
                ('locality', models.CharField(blank=True, max_length=9000, null=True)),
                ('institute', models.CharField(blank=True, max_length=4000, null=True)),
                ('herbarium_code', models.CharField(blank=True, max_length=9000, null=True)),
                ('barcode', models.CharField(blank=True, max_length=30000, null=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('country_iso3', models.CharField(blank=True, max_length=150, null=True)),
                ('coordinate_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'distribution_species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('idextraction', models.AutoField(primary_key=True, serialize=False)),
                ('extrrun_numint', models.IntegerField(blank=True, null=True)),
                ('extrun_numext', models.IntegerField(blank=True, null=True)),
                ('quantity_adn', models.FloatField(blank=True, null=True)),
                ('gel', models.IntegerField(blank=True, null=True)),
                ('shearing', models.IntegerField(blank=True, null=True)),
                ('intlib', models.IntegerField(blank=True, null=True)),
                ('sample_qtity_nbr', models.IntegerField(blank=True, null=True)),
                ('tcs', models.CharField(max_length=150)),
                ('comment_extr', models.CharField(blank=True, max_length=500, null=True)),
                ('barcode', models.CharField(blank=True, max_length=150, null=True)),
                ('date_extraction', models.DateField(blank=True, null=True)),
                ('rarete', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'extraction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtractionSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'extraction_species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('idgenus', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('idtribe', models.IntegerField()),
                ('namegenus', models.CharField(max_length=150)),
                ('linkpowo', models.CharField(blank=True, max_length=950, null=True)),
            ],
            options={
                'db_table': 'genus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('idindex', models.AutoField(primary_key=True, serialize=False)),
                ('grouptag', models.CharField(blank=True, max_length=150, null=True)),
                ('indexnumber', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('idlocality', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'locality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nirs',
            fields=[
                ('idnirs', models.AutoField(primary_key=True, serialize=False)),
                ('codenirs', models.CharField(max_length=150)),
                ('barcode', models.CharField(max_length=150)),
                ('link_img_nirs', models.CharField(blank=True, max_length=150, null=True)),
                ('comment_nirs', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'nirs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderSendersample',
            fields=[
                ('idprovider', models.AutoField(primary_key=True, serialize=False)),
                ('nameprovider', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'provider_sendersample',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('idresume', models.AutoField(primary_key=True, serialize=False)),
                ('numberspecies', models.IntegerField(blank=True, null=True)),
                ('continent', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'resume',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('idrun', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'run',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RunIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'run_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('idspecies', models.AutoField(primary_key=True, serialize=False)),
                ('idgenus', models.IntegerField()),
                ('namespecies', models.CharField(max_length=150)),
                ('commentary', models.CharField(blank=True, max_length=800, null=True)),
                ('tcs', models.CharField(max_length=150)),
                ('keepsampl_method', models.CharField(max_length=30)),
                ('idlocation_species', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpeciesPhit',
            fields=[
                ('idspecies_phit', models.AutoField(primary_key=True, serialize=False)),
                ('namespecies_phit', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'species_phit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Speciesv2',
            fields=[
                ('idspeciesv2', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('idgenus', models.CharField(max_length=150)),
                ('namespeciesv2', models.CharField(blank=True, max_length=150, null=True)),
                ('nameepithet', models.CharField(blank=True, max_length=150, null=True)),
                ('authorspeciesv2', models.CharField(blank=True, max_length=150, null=True)),
                ('commentsv2', models.CharField(blank=True, max_length=1500, null=True)),
                ('acceptornot', models.CharField(blank=True, max_length=150, null=True)),
                ('namefamily', models.CharField(blank=True, max_length=150, null=True)),
                ('nametribe', models.CharField(blank=True, max_length=150, null=True)),
                ('validforproject', models.CharField(blank=True, max_length=150, null=True)),
                ('linkpowo', models.CharField(blank=True, max_length=950, null=True)),
            ],
            options={
                'db_table': 'speciesv2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('idspecimen', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('idgenus', models.CharField(blank=True, max_length=150, null=True)),
                ('namespecimen', models.CharField(blank=True, max_length=150, null=True)),
                ('nameepithet', models.CharField(blank=True, max_length=150, null=True)),
                ('keepsamplemethod', models.CharField(blank=True, max_length=150, null=True)),
                ('nametribe', models.CharField(blank=True, max_length=150, null=True)),
                ('idspeciesv2', models.CharField(blank=True, max_length=150, null=True)),
                ('comments', models.CharField(blank=True, max_length=800, null=True)),
                ('idlocality', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'specimen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('idstatus', models.AutoField(primary_key=True, serialize=False)),
                ('typestatus', models.CharField(max_length=150)),
                ('numstatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subfamily',
            fields=[
                ('idsubfamily', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('namesubfamily', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'subfamily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Synonymous',
            fields=[
                ('idsynonymous', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('namespecies', models.CharField(blank=True, max_length=150, null=True)),
                ('synonymous', models.CharField(blank=True, max_length=150, null=True)),
                ('comments', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'synonymous',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('idtag', models.AutoField(primary_key=True, serialize=False)),
                ('grouptag', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('idtribe', models.AutoField(primary_key=True, serialize=False)),
                ('idsubfamily', models.IntegerField()),
                ('nametribe', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'tribe',
                'managed': False,
            },
        ),
    ]
